FROM python:3.10

WORKDIR /app

COPY ../requirements.txt .
RUN pip install -r requirements.txt
COPY ../src ./src

ENV DB_URL=postgresql://postgres:postgress@localhost:5432/postgres

ENTRYPOINT [ "python3", "-m" , "src.main"]
