/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: H/uG47THL3RSPij/8ooWExjbbTb+MOIO3rt838ImcPxP0801ZOsaGq2U7kc/jBATzUVT581/g3EH5xS1gj5jwA==
 */

/* eslint-disable */
// tslint:disable

interface EventTxHashes {
  solver: string;
  tx_hash: string;
}
export default EventTxHashes;

interface EventTxHashes_InsertParameters {
  solver: string;
  tx_hash: string;
}
export type { EventTxHashes_InsertParameters };
