/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: CnyU+lcopIYKMwXn4IWU2ap9njlIoHZ61BjFmzL3Xg6RAaqODi+GPyR4yJ087LvFYOby1UNtDN0Uf2gb3k0afw==
 */

/* eslint-disable */
// tslint:disable

import EventTxHashes, {
  EventTxHashes_InsertParameters,
} from "./event_tx_hashes";

interface DatabaseSchema {
  event_tx_hashes: {
    record: EventTxHashes;
    insert: EventTxHashes_InsertParameters;
  };
}
export default DatabaseSchema;

function serializeValue(
  _tableName: string,
  _columnName: string,
  value: unknown
): unknown {
  return value;
}
export { serializeValue };

export type { EventTxHashes, EventTxHashes_InsertParameters };
